// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6VtQpP4xmxPjI5GzN0nETZDZEw79_7WQ',
    appId: '1:1020693936380:web:e6990c9718dde192cf7f79',
    messagingSenderId: '1020693936380',
    projectId: 'last-task3',
    authDomain: 'last-task3.firebaseapp.com',
    storageBucket: 'last-task3.appspot.com',
    measurementId: 'G-0EQDL56F2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_sxaBjufIth9HMw6ujUuw_Ci9UC9-Fg',
    appId: '1:1020693936380:android:9c3e60b4bc262a72cf7f79',
    messagingSenderId: '1020693936380',
    projectId: 'last-task3',
    storageBucket: 'last-task3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvmDYS0ScWypun-h7bVrlFzIiOzba_LeQ',
    appId: '1:1020693936380:ios:c54a8c54aa5bbe6ccf7f79',
    messagingSenderId: '1020693936380',
    projectId: 'last-task3',
    storageBucket: 'last-task3.appspot.com',
    iosClientId: '1020693936380-vkkpf6m0lssmhdrncvjm79blf82tv00l.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvmDYS0ScWypun-h7bVrlFzIiOzba_LeQ',
    appId: '1:1020693936380:ios:c54a8c54aa5bbe6ccf7f79',
    messagingSenderId: '1020693936380',
    projectId: 'last-task3',
    storageBucket: 'last-task3.appspot.com',
    iosClientId: '1020693936380-vkkpf6m0lssmhdrncvjm79blf82tv00l.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystore',
  );
}
